(function () {
  window.NcqqDashboardMockData = {
    generated_at: Date.now() / 1000,
    default_manager: "local",
    managers: [
      {
        id: "local",
        name: "本地面板",
        url: "http://127.0.0.1:8080",
        is_default: true,
        health: { ok: true, status: "ok", docker: true, state_engine: true, degraded_reasons: [] },
        bots: { ok: true, total: 10, online: 5 },
        instances: {
          ok: true,
          running: 7,
          online: 5,
          total: 10,
          items: [
            {
              name: "baka9",
              display_name: "baka9",
              status: "running",
              running: true,
              bot_online: true,
              uin: "315000754",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=315000754&s=100",
              login_stage: "logged_in",
              login_method: "sdk_ws",
              heartbeat_ts: Date.now() / 1000 - 60,
            },
            {
              name: "698076448",
              display_name: "698076448",
              status: "running",
              running: true,
              bot_online: true,
              uin: "171000139",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=171000139&s=100",
              login_stage: "logged_in",
            },
            {
              name: "788952021",
              display_name: "788952021",
              status: "exited",
              running: false,
              bot_online: false,
              uin: "",
              avatar: "",
              login_stage: "offline",
            },
            {
              name: "1154121306",
              display_name: "1154121306",
              status: "exited",
              running: false,
              bot_online: false,
              uin: "",
              avatar: "",
              login_stage: "offline",
            },
            {
              name: "miya",
              display_name: "miya",
              status: "running",
              running: true,
              bot_online: false,
              uin: "240000846",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=240000846&s=100",
              login_stage: "offline",
              heartbeat_ts: Date.now() / 1000 - 5400,
            },
            {
              name: "moka",
              display_name: "moka",
              status: "running",
              running: true,
              bot_online: true,
              uin: "100000001",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=100000001&s=100",
            },
            {
              name: "kira",
              display_name: "kira",
              status: "running",
              running: true,
              bot_online: false,
              uin: "100000002",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=100000002&s=100",
            },
            { name: "nana", display_name: "nana", status: "exited", running: false, bot_online: false, uin: "", avatar: "" },
            {
              name: "sora",
              display_name: "sora",
              status: "running",
              running: true,
              bot_online: true,
              uin: "100000003",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=100000003&s=100",
            },
            {
              name: "yuki",
              display_name: "yuki",
              status: "running",
              running: true,
              bot_online: true,
              uin: "100000004",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=100000004&s=100",
            },
          ],
        },
      },
      {
        id: "cloud",
        name: "云端面板",
        url: "https://ncqq.example.com",
        is_default: false,
        health: { ok: true, status: "degraded", docker: true, state_engine: true, degraded_reasons: ["heartbeat"] },
        bots: { ok: true, total: 3, online: 1 },
        instances: {
          ok: true,
          running: 2,
          online: 1,
          total: 3,
          items: [
            {
              name: "demo",
              display_name: "demo",
              status: "running",
              running: true,
              bot_online: true,
              uin: "112233445",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=112233445&s=100",
            },
            {
              name: "ops",
              display_name: "ops",
              status: "running",
              running: true,
              bot_online: false,
              uin: "223344556",
              avatar: "https://q1.qlogo.cn/g?b=qq&nk=223344556&s=100",
            },
            { name: "spare", display_name: "spare", status: "exited", running: false, bot_online: false, uin: "", avatar: "" },
          ],
        },
      },
    ],
    approvals: [
      {
        approval_id: "AB12CD",
        action: "delete",
        description: "销毁实例 cloud/demo",
        requester_qq: "123456",
        group_id: "987654",
        age_seconds: 420,
        manager_id: "cloud",
        instance_name: "demo",
      },
    ],
    bindings: [
      { qq: "123456", nickname: "Alice", instances: ["local/baka9", "cloud/demo"] },
      { qq: "654321", nickname: "", instances: ["local/miya"] },
      { qq: "100001", nickname: "B01", instances: ["local/moka"] },
      { qq: "100002", nickname: "B02", instances: ["local/kira"] },
      { qq: "100003", nickname: "B03", instances: ["local/nana"] },
      { qq: "100004", nickname: "B04", instances: ["cloud/ops"] },
      { qq: "100005", nickname: "B05", instances: ["cloud/spare"] },
      { qq: "100006", nickname: "B06", instances: ["local/698076448"] },
      { qq: "100007", nickname: "B07", instances: ["local/sora"] },
      { qq: "100008", nickname: "B08", instances: ["local/yuki"] },
      { qq: "100009", nickname: "B09", instances: ["cloud/demo"] },
    ],
  };
})();
